languages:
   Python: true
engines:
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  radon:
    enabled: true
  fixme:
    enabled: true
ratings:
   paths:
   - jarvis/**
   - examples/**
   - "**.py"
exclude_paths:
- "**.md"
- "**.rst"
- "setup.py"
- "**.yml"
