from chatterbot import ChatBot

class JarvisChatBot:
    global jarvis_chatterbot

    def __init__( self ):
        """ Initializer """

        global jarvis_chatterbot

        jarvis_chatterbot = ChatBot("Jarvis",
            storage_adapter="chatterbot.adapters.storage.JsonDatabaseAdapter",
            logic_adapter="chatterbot.adapters.logic.ClosestMatchAdapter",
            io_adapter="chatterbot.adapters.io.TerminalAdapter",
            database="database.db")


    def generate_response( self, user_input ):
        """ Returns the result generated by ChatterBot """

        global jarvis_chatterbot

        response = jarvis_chatterbot.get_response( user_input )

        return response
