from chatterbot import ChatBot

class JarvisChatBot:

    def __init__( self ):
        """ Initializer """

        self.jarvis_chatterbot = ChatBot("Jarvis",
            storage_adapter="chatterbot.adapters.storage.JsonDatabaseAdapter",
            logic_adapter="chatterbot.adapters.logic.ClosestMatchAdapter",
            io_adapter="chatterbot.adapters.io.NoOutputAdapter",
            database="database.db")


    def generate_response( self, user_input ):
        """ Returns the result generated by ChatterBot """

        response = self.jarvis_chatterbot.get_response( user_input )

        return response
